### ISSUE TITLE
python 3.12/11 installation

### ISSUE THREAD

**Issue by GeneriicName** [glmcdona/binary2strings#22]
when trying to pip install `flare-floss` in python 3.12 (windows 11) i get the following error

```
PS C:\Users\user> py -m pip install flare-floss
Collecting flare-floss
  Using cached flare_floss-3.0.1-py3-none-any.whl.metadata (5.5 kB)
Collecting tabulate==0.9.0 (from flare-floss)
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting vivisect==1.1.1 (from flare-floss)
  Using cached vivisect-1.1.1-py3-none-any.whl.metadata (2.8 kB)
Collecting viv-utils==0.7.9 (from viv-utils[flirt]==0.7.9->flare-floss)
  Using cached viv_utils-0.7.9-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting pydantic==1.10.9 (from flare-floss)
  Using cached pydantic-1.10.9-py3-none-any.whl.metadata (147 kB)
Collecting tqdm==4.65.0 (from flare-floss)
  Using cached tqdm-4.65.0-py3-none-any.whl.metadata (56 kB)
Collecting networkx==3.1 (from flare-floss)
  Using cached networkx-3.1-py3-none-any.whl.metadata (5.3 kB)
Collecting halo==0.0.31 (from flare-floss)
  Using cached halo-0.0.31.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting rich==13.4.2 (from flare-floss)
  Using cached rich-13.4.2-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pefile>=2022.5.30 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from flare-floss) (2023.2.7)
Collecting binary2strings==0.1.13 (from flare-floss)
  Using cached binary2strings-0.1.13.tar.gz (59 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-_0up553l\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-_0up553l\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-_0up553l\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 30, in <module>
        File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1255.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8c in position 2769: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
which originated from `binary2strings` whcih is a dependency for the `flare-floss` package
i tried to install ` pip install binary2strings` and got the same error

tried it on two computers, with windows11 and windows 10, both python 3.12 and python3.11, same result
and i used both cmd, PowerShell and the terminal of pycharm (also PS, in venv)

i prefer not to downgrade further, hoping anyone has a soltuion
thanks in advance!

**Comment by glmcdona** [comment]
Thanks for the report, will have a look into it.

**Comment by glmcdona** [comment]
Note, that I've tried to replicate it unsuccessfully here so far. On Windows 11 I created a anaconda environment on python 3.13, and `pip install binary2strings` works correctly. Must be some build tool difference (maybe a compiler difference?). Will keep investigating...

**Comment by GeneriicName** [comment]
> Note, that I've tried to replicate it unsuccessfully here so far. On Windows 11 I created a anaconda environment on python 3.13, and `pip install binary2strings` works correctly. Must be some build tool difference (maybe a compiler difference?). Will keep investigating...

Thank you for looking in to it, I'm really looking up to using your lib!

If any information is needed about my environment or python version etc, I will be happy to provide.

**Comment by glmcdona** [comment]
Thanks! It seems the error is in setuptools for a character decode error on maybe a multilingual character. My best guess is that the long-description of my package containing multi-lingual characters is breaking setuptools, since I do include some mandarin utf-8 characters in the long description of the project:
https://github.com/glmcdona/binary2strings/blob/02f0c983aeede7ed9acbee96a43f9142dc7ba404/setup.py#L30

Could you list your package versions by any chance? Curious what version of setuptools you are using. `pip freeze`

**Comment by GeneriicName** [comment]
> Thanks! It seems the error is in setuptools for a character decode error on maybe a multilingual character. My best guess is that the long-description of my package containing multi-lingual characters is breaking setuptools, since I do include some mandarin utf-8 characters in the long description of the project:
> 
> https://github.com/glmcdona/binary2strings/blob/02f0c983aeede7ed9acbee96a43f9142dc7ba404/setup.py#L30
> 
> Could you list your package versions by any chance? Curious what version of setuptools you are using. `pip freeze`

yes! sorry for the delayed response
I have setuptools version 69.2.0
this is for my venv, its quite a mess as im just using it to explore stuff
```
(.venv) PS C:\Users\user\Desktop\python\website__\pythonProject> pip freeze
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\attrs-23.2.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\bs4-0.0.2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\h11-0.14.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\jwscraper-1.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\outcome-1.3.0.post0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\pysocks-1.7.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\selenium-4.17.2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\sniffio-1.3.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\trio-0.24.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\trio_websocket-0.11.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\user\desktop\python\website__\pythonproject\.venv\lib\site-packages\wsproto-1.2.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
altgraph==0.17.4
antiword==0.1.0
appdirs==1.4.4
arabic-reshaper==3.0.0
argcomplete==1.10.3
asgiref==3.7.2
asn1crypto==1.5.1
attrs==23.2.0
audio-extract==0.6.0
Automat==22.10.0
av==11.0.0
beautifulsoup4==4.8.2
bs4==0.0.2
certifi==2023.11.17
cffi==1.16.0
cfscrape==2.1.1
chardet==3.0.4
charset-normalizer==3.3.2
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
compressed_rtf==1.0.6
constantly==23.10.4
crispy-bootstrap4==2024.1
crispy-bootstrap5==2024.2
cryptography==42.0.1
cssselect==1.2.0
cssselect2==0.7.0
decorator==4.4.2
defusedxml==0.7.1
Deprecated==1.2.14
Django==4.2.10
django-ace==1.32.4
django-allauth==0.61.1
django-appconf==1.0.6
django-audit-log==0.7.0
django-auditlog==2.3.0
django-axes==6.3.0
django-bootstrap-v5==1.0.11
django-classy-tags==4.1.0
django-cms==4.1.0
django-cors-headers==4.3.1
django-crispy-forms==2.1
django-easy-pdf==0.1.1
django-entangled==0.5.4
django-extensions==3.2.3
django-filer==3.1.1
django-formtools==2.5.1
django-fsm==2.8.1
django-ipware==6.0.4
django-parler==2.3
django-polymorphic==3.1.0
django-recaptcha==4.0.0
django-sekizai==4.1.0
django-select2==8.1.2
django-treebeard==4.7
django-utils==0.0.2
djangocms-admin-style==3.2.7
djangocms-alias==2.0.0
djangocms-attributes-field==3.0.0
djangocms-frontend==1.2.2
djangocms-text-ckeditor==5.1.5
djangocms-versioning==2.0.0
djangorestframework==3.14.0
docx2pdf==0.1.8
docx2txt==0.8
easy-thumbnails==2.8.5
easypdf==1.0
ebcdic==1.1.1
extract-msg==0.28.7
fade==0.0.9
fake-useragent==1.4.0
ffmpeg==1.4
ffmpeg-downloader==0.3.0
ffmpeg-python==0.2.0
filelock==3.13.1
filetype==1.2.0
fire==0.5.0
fonttools==4.47.2
fpdf2==2.7.7
future==0.18.3
gratient==0.4
greenlet==3.0.3
grope==2.0.1
h11==0.14.0
html2text==2020.1.16
html5lib==1.1
hyperlink==21.0.0
icoextract==0.1.4
idna==3.6
imageio==2.33.1
imageio-ffmpeg==0.4.8
IMAPClient==2.1.0
img2pdf==0.5.1
importlib-metadata==7.0.1
incremental==22.10.0
install_playwright==0.0.1
itemadapter==0.8.0
itemloaders==1.1.0
jmespath==1.0.1
jwscraper==1.0
kaitaistruct==0.10
lazy_loader==0.3
lxml==5.1.0
MarkupSafe==2.1.5
moviepy==1.0.3
mutagen==1.46.0
networkx==3.2.1
numpy==1.26.3
oauthlib==3.2.2
olefile==0.47
opencv-python-headless==4.9.0.80
oscrypto==1.3.0
outcome==1.3.0.post0
packaging==23.2
parse==1.20.1
parsel==1.8.1
pdf2docx==0.5.8
pdf2pptx==1.0.5
pdfminer.six==20191110
pe-tools==0.3.10
pefile==2023.2.7
pikepdf==8.11.2
pillow==10.2.0
platformdirs==4.2.0
playwright==1.41.1
plum-dispatch==1.7.4
proglog==0.1.10
Protego==0.3.0
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
pycryptodome==3.20.0
PyDispatcher==2.0.7
pydub==0.25.1
pydumpck==1.5.113
pyee==8.2.2
pyHanko==0.21.0
pyhanko-certvalidator==0.26.3
pyinstaller==6.3.0
pyinstaller-hooks-contrib==2024.0
PyJWT==2.8.0
PyMuPDF==1.23.20
PyMuPDFb==1.23.9
pyOpenSSL==24.0.0
pypdf==4.0.0
PyPDF2==3.0.1
pypng==0.20220715.0
pyppeteer==1.0.2
pyquery==2.0.0
PySocks==1.7.1
python-bidi==0.4.2
python-dateutil==2.8.2
python-docx==1.1.0
python-ipware==2.0.2
python-pptx==0.6.23
python3-openid==3.2.0
pythonnet==3.0.3
pytz==2024.1
pywin32==306
pywin32-ctypes==0.2.2
PyYAML==6.0.1
qrcode==7.4.2
queuelib==1.6.2
reportlab==4.0.9
requests==2.31.0
requests-file==2.0.0
requests-html==0.10.0
requests-oauthlib==1.4.0
scikit-image==0.22.0
scipy==1.12.0
Scrapy==2.11.1
selenium==4.17.2
service-identity==24.1.0
setuptools==69.2.0
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.5
spark-parser==1.8.9
SpeechRecognition==3.8.1
Spire.Pdf==10.1.1
sqlparse==0.4.4
svglib==1.5.1
svgtrace==2024
termcolor==2.4.0
tifffile==2024.1.30
tinyaes==1.1.0
tinycss2==1.2.1
tldextract==5.1.1
tqdm==4.66.1
trio==0.24.0
trio-websocket==0.11.1
Twisted==23.10.0
twisted-iocpsupport==1.0.4
typing_extensions==4.9.0
tzdata==2023.4
tzlocal==5.2
uncompyle6==3.7.4
uritools==4.0.2
urllib3==1.26.18
validators==0.22.0
w3lib==2.1.2
Wand==0.6.13
webencodings==0.5.1
websockets==10.4
Werkzeug==3.0.1
wheel==0.43.0
whitenoise==6.6.0
wrapt==1.16.0
wsproto==1.2.0
xdis==5.0.13
xhtml2pdf==0.2.14
xlrd==1.2.0
XlsxWriter==3.1.9
zipp==3.17.0
zope.interface==6.1

```
and this is my global packages
```
PS C:\Users\user> py -m pip freeze
aiohttp==3.9.3
aiosignal==1.3.1
asgiref==3.7.2
attrs==23.2.0
certifi==2023.11.17
click==8.1.7
colorama==0.4.6
Deprecated==1.2.14
distlib==0.3.8
Django==5.0.2
django-extensions==3.2.3
fastjsonschema==2.19.1
filelock==3.13.1
frozenlist==1.4.1
future==1.0.0
icoextract==0.1.4
idna==3.6
img2pdf==0.5.1
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter_core==5.7.1
lxml==5.1.0
MarkupSafe==2.1.5
multidict==6.0.5
nbformat==5.9.2
packaging==23.2
pefile==2023.2.7
pigar==2.1.3
pikepdf==8.11.2
pillow==10.2.0
pipenv==2023.11.17
platformdirs==4.1.0
psutil==5.9.8
pyad==0.6.0
pybind11==2.11.1
pyodbc==5.1.0
PyQt6==6.6.1
PyQt6-Qt6==6.6.2
PyQt6-sip==13.6.0
pywin32==306
referencing==0.33.0
rpds-py==0.18.0
setuptools==69.2.0
sqlparse==0.4.4
traitlets==5.14.1
tzdata==2024.1
validators==0.22.0
virtualenv==20.25.0
Werkzeug==3.0.1
wheel==0.43.0
WMI==1.5.1
wrapt==1.16.0
yarl==1.9.4
```

**Comment by GeneriicName** [comment]
Hello, I don't mean to be a bother, but if you have any update in the matter I'd love to know :-)

And thank you very much for looking into it, I appriacate it!

**Comment by glmcdona** [comment]
@GeneriicName, your setuptools looks good. Curious, what language is your OS?

I'm not able to reproduce the error locally, but I created a branch that may fix the issue if my hunch is right. By any chance could you try checking out branch `glmcdona/test_multilingual_fix`, and installing it using `pip install .`? Full set of commands should be:
```
git clone https://github.com/glmcdona/binary2strings
cd binary2strings
git checkout glmcdona/test_multilingual_fix
pip install .
```

Thanks!

**Comment by GeneriicName** [comment]
that worked perfectly, thnk you very much!!

and my OS lang is hebrew, maybe thats the root of the issue

anyways, thanks alot, i really do appricate it!

**Comment by glmcdona** [comment]
Great, glad it fixed it! My best guess is the OS language is breaking it somehow. Odd that it's an international edition of Windows that breaks because of multi-lingual characters in the package description (Chinese Mandarin characters in project description). I'll publish a new version where it doesn't have the multi-lingual characters in the package description.
